### ISSUE TITLE
unicode shortcuts are not working anymore

### ISSUE THREAD

**Issue by leodemoura** [leanprover/leanprover.github.io#49]
In the past, we could use shortcuts such as `\to`, `\nat` and `\fun` in the Lean web version.
It doesn't seem to work anymore. I tried in different browsers on Windows and Linux.
It doesn't work in any of them.

@soonhokong Do you have any idea why it doesn't work anymore? 

@avigad Does it work for you?

Thanks.

**Comment by soonhokong** [comment]
It's because [js/input-method.js](https://github.com/leanprover/tutorial/blob/gh-pages/js/input-method.js) is not properly generated (now it's empty). I'll fix it soon.

**Comment by leodemoura** [comment]
Thanks.

**Comment by soonhokong** [comment]
I manually update `js/input-method.js`. It should work now.

We automatically generate this file from travis-ci, something changes and now it breaks. I'll investigate it and fix the problem soon.

**Comment by leodemoura** [comment]
BTW, Bryan @parno was the one that found the problem.

**Comment by leodemoura** [comment]
> I manually update js/input-method.js. It should work now.

I cleared the cache, and tried again. It still doesn't work. Does it take a few minutes for the change to propagate?

**Comment by soonhokong** [comment]
@leodemoura, there was a problem. Now it should work. I checked that it worked on my machines.

**Comment by avigad** [comment]
It is working for me too.

**Comment by leodemoura** [comment]
@soonhokong It is working for me now. Thanks for fixing it!

@parno The problem was fixed.

**Comment by parno** [comment]
Yep, working for me as well.  Thanks for the fix!

**Comment by soonhokong** [comment]
FYI, this fix was a temporary one. There is still a problem in Travis-CI and I'm working with them to fix it (mainly to upgrade its emacs-24 installation from the currently deprecated one). When it's done, I'll let you know with another comment. Until then, I'll do manual updates of `js/input-method.el` file whenever we have a new commit on the `leanprover/tutorial` repo.
